Watching for file changes with StatReloader
Authentication failed. No user found with email: lhu0770@gmail.com.
Error sending verification email: (534, b'5.7.9 Please log in with your web browser and then try again. For more\n5.7.9 information, go to\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired d9443c01a7336-1fac15389b3sm57519565ad.121 - gsmtp')
Internal Server Error: /login/send_verification_email/
Error sending verification email: (534, b'5.7.9 Please log in with your web browser and then try again. For more\n5.7.9 information, go to\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired d9443c01a7336-1fac1535d58sm57627025ad.125 - gsmtp')
Internal Server Error: /login/send_verification_email/
Watching for file changes with StatReloader
Not Found: /favicon.ico
Error sending verification email: (534, b'5.7.9 Please log in with your web browser and then try again. For more\n5.7.9 information, go to\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired 41be03b00d2f7-72c6b39809fsm4635786a12.52 - gsmtp')
Internal Server Error: /login/send_verification_email/
E:\빅프로젝트_34조\bigproject28\aivle_big\settings.py changed, reloading.
Watching for file changes with StatReloader
Error sending verification email: (534, b'5.7.9 Please log in with your web browser and then try again. For more\n5.7.9 information, go to\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired d9443c01a7336-1faceb78c6csm50141135ad.271 - gsmtp')
Internal Server Error: /login/send_verification_email/
Error sending verification email: (534, b'5.7.9 Please log in with your web browser and then try again. For more\n5.7.9 information, go to\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired d9443c01a7336-1fac1598bedsm59262055ad.253 - gsmtp')
Internal Server Error: /login/send_verification_email/
E:\빅프로젝트_34조\bigproject28\aivle_big\settings.py changed, reloading.
Watching for file changes with StatReloader
Error sending verification email: (534, b'5.7.9 Please log in with your web browser and then try again. For more\n5.7.9 information, go to\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired d9443c01a7336-1fac10e37a8sm59512805ad.88 - gsmtp')
Internal Server Error: /login/send_verification_email/
E:\빅프로젝트_34조\bigproject28\aivle_big\settings.py changed, reloading.
Watching for file changes with StatReloader
Error sending verification email: (534, b'5.7.9 Please log in with your web browser and then try again. For more\n5.7.9 information, go to\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired d9443c01a7336-1fac1598bedsm59293275ad.253 - gsmtp')
Internal Server Error: /login/send_verification_email/
Watching for file changes with StatReloader
Error sending verification email: (534, b'5.7.9 Please log in with your web browser and then try again. For more\n5.7.9 information, go to\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired d9443c01a7336-1fac1537373sm57498955ad.135 - gsmtp')
Internal Server Error: /login/send_verification_email/
E:\빅프로젝트_34조\bigproject28\aivle_big\settings.py changed, reloading.
Watching for file changes with StatReloader
Error sending verification email: (534, b'5.7.9 Please log in with your web browser and then try again. For more\n5.7.9 information, go to\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired d2e1a72fcca58-70867f642fesm5505274b3a.166 - gsmtp')
Internal Server Error: /login/send_verification_email/
E:\빅프로젝트_34조\bigproject28\aivle_big\settings.py changed, reloading.
Watching for file changes with StatReloader
Error sending verification email: (534, b'5.7.9 Please log in with your web browser and then try again. For more\n5.7.9 information, go to\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired d9443c01a7336-1fac11d9685sm57922585ad.111 - gsmtp')
Internal Server Error: /login/send_verification_email/
Watching for file changes with StatReloader
Error sending verification email: (534, b'5.7.9 Please log in with your web browser and then try again. For more\n5.7.9 information, go to\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired 98e67ed59e1d1-2c91d3eb774sm6087351a91.53 - gsmtp')
Internal Server Error: /login/send_verification_email/
E:\빅프로젝트_34조\bigproject28\aivle_big\settings.py changed, reloading.
Watching for file changes with StatReloader
Error sending verification email: (534, b'5.7.9 Please log in with your web browser and then try again. For more\n5.7.9 information, go to\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired 98e67ed59e1d1-2c91d3ea46fsm6147870a91.52 - gsmtp')
Internal Server Error: /login/send_verification_email/
Watching for file changes with StatReloader
Error sending verification email: (534, b'5.7.9 Please log in with your web browser and then try again. For more\n5.7.9 information, go to\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired d2e1a72fcca58-70801007c62sm5877922b3a.0 - gsmtp')
Internal Server Error: /login/send_verification_email/
Error sending verification email: (534, b'5.7.9 Please log in with your web browser and then try again. For more\n5.7.9 information, go to\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired d9443c01a7336-1fac15694b2sm58129285ad.190 - gsmtp')
Internal Server Error: /login/send_verification_email/
Watching for file changes with StatReloader
Error sending verification email: (534, b'5.7.9 Please log in with your web browser and then try again. For more\n5.7.9 information, go to\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired d9443c01a7336-1fac1535ca7sm58310065ad.153 - gsmtp')
Internal Server Error: /login/send_verification_email/
Error sending verification email: (534, b'5.7.9 Please log in with your web browser and then try again. For more\n5.7.9 information, go to\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired d9443c01a7336-1fac1598d35sm58075695ad.285 - gsmtp')
Internal Server Error: /login/send_verification_email/
E:\빅프로젝트_34조\bigproject28\aivle_big\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Error sending verification email: (534, b'5.7.9 Please log in with your web browser and then try again. For more\n5.7.9 information, go to\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired d2e1a72fcca58-70803ecfb90sm5839512b3a.139 - gsmtp')
Internal Server Error: /login/send_verification_email/
E:\빅프로젝트_34조\bigproject28\aivle_big\settings.py changed, reloading.
Watching for file changes with StatReloader
Error sending verification email: (534, b'5.7.9 Please log in with your web browser and then try again. For more\n5.7.9 information, go to\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired 98e67ed59e1d1-2c91ce1a292sm6131455a91.7 - gsmtp')
Internal Server Error: /login/send_verification_email/
E:\빅프로젝트_34조\bigproject28\aivle_big\settings.py changed, reloading.
Watching for file changes with StatReloader
Error sending verification email: (534, b'5.7.9 Please log in with your web browser and then try again. For more\n5.7.9 information, go to\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired d9443c01a7336-1fad304311csm47365455ad.31 - gsmtp')
Internal Server Error: /login/send_verification_email/
Error sending verification email: (534, b'5.7.9 Please log in with your web browser and then try again. For more\n5.7.9 information, go to\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired d9443c01a7336-1fac1535cbdsm58653595ad.134 - gsmtp')
Internal Server Error: /login/send_verification_email/
Error sending verification email: (534, b'5.7.9 Please log in with your web browser and then try again. For more\n5.7.9 information, go to\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired 41be03b00d2f7-72c6d102b65sm4660323a12.77 - gsmtp')
Internal Server Error: /login/send_verification_email/
E:\빅프로젝트_34조\bigproject28\aivle_big\settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /community/
Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\asgiref\local.py", line 89, in _lock_storage
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\utils\connection.py", line 58, in __getitem__
    return getattr(self._connections, alias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\asgiref\local.py", line 118, in __getattr__
    return getattr(storage, key)
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_thread._local' object has no attribute 'community_db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\빅프로젝트_34조\bigproject28\community\views.py", line 11, in post_list
    return render(request, 'post_list.html', {'posts':
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\defaulttags.py", line 198, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 88, in __iter__
    compiler = queryset.query.get_compiler(using=db)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\sql\query.py", line 361, in get_compiler
    connection = connections[using]
                 ~~~~~~~~~~~^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\utils\connection.py", line 61, in __getitem__
    raise self.exception_class(f"The connection '{alias}' doesn't exist.")
django.utils.connection.ConnectionDoesNotExist: The connection 'community_db' doesn't exist.
User found with email: lhu0770@gmail.com. Username: lhu0770
User lhu0770@gmail.com authenticated successfully.
Internal Server Error: /community/
Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\asgiref\local.py", line 89, in _lock_storage
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\utils\connection.py", line 58, in __getitem__
    return getattr(self._connections, alias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\asgiref\local.py", line 118, in __getattr__
    return getattr(storage, key)
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_thread._local' object has no attribute 'community_db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\빅프로젝트_34조\bigproject28\community\views.py", line 11, in post_list
    return render(request, 'post_list.html', {'posts':
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\defaulttags.py", line 198, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 88, in __iter__
    compiler = queryset.query.get_compiler(using=db)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\sql\query.py", line 361, in get_compiler
    connection = connections[using]
                 ~~~~~~~~~~~^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\utils\connection.py", line 61, in __getitem__
    raise self.exception_class(f"The connection '{alias}' doesn't exist.")
django.utils.connection.ConnectionDoesNotExist: The connection 'community_db' doesn't exist.
Attempting to save post: 1 for user: lhu0770, Email: lhu0770@gmail.com
Error saving post: The connection 'community_db' doesn't exist.
Attempting to save post: 1 for user: lhu0770, Email: lhu0770@gmail.com
Error saving post: The connection 'community_db' doesn't exist.
Attempting to save post: 1 for user: lhu0770, Email: lhu0770@gmail.com
Error saving post: The connection 'community_db' doesn't exist.
E:\빅프로젝트_34조\bigproject28\community\views.py changed, reloading.
Watching for file changes with StatReloader
Attempting to save post: 1 for user: lhu0770, Email: lhu0770@gmail.com
Post saved successfully with ID: 1
Internal Server Error: /community/post/1/
Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: post_detail() got an unexpected keyword argument 'pk'
E:\빅프로젝트_34조\bigproject28\community\urls.py changed, reloading.
Watching for file changes with StatReloader
E:\빅프로젝트_34조\bigproject28\community\views.py changed, reloading.
Watching for file changes with StatReloader
Attempting to save post: 1 for user: lhu0770, Email: lhu0770@gmail.com
Post saved successfully with ID: 2
Attempting to save post: 2 for user: lhu0770, Email: lhu0770@gmail.com
Post saved successfully with ID: 3
Watching for file changes with StatReloader
Authentication failed. No user found with email: lhu0770@gmail.com.
User found with email: lhu0770@gmail.com. Username: lhu0770
User lhu0770@gmail.com authenticated successfully.
Internal Server Error: /community/
Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: 오류:  "post" 이름의 릴레이션(relation)이 없습니다
LINE 1: ...ent", "post"."creation_date", "post"."post_type" FROM "post"
                                                                 ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\빅프로젝트_34조\bigproject28\community\views.py", line 11, in post_list
    return render(request, 'post_list.html', {'posts': posts})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\defaulttags.py", line 198, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: 오류:  "post" 이름의 릴레이션(relation)이 없습니다
LINE 1: ...ent", "post"."creation_date", "post"."post_type" FROM "post"
                                                                 ^

E:\빅프로젝트_34조\bigproject28\community\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /community/
Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: 오류:  "post" 이름의 릴레이션(relation)이 없습니다
LINE 1: ...ent", "post"."creation_date", "post"."post_type" FROM "post"
                                                                 ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\빅프로젝트_34조\bigproject28\community\views.py", line 11, in post_list
    return render(request, 'post_list.html', {'posts': posts})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\defaulttags.py", line 198, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: 오류:  "post" 이름의 릴레이션(relation)이 없습니다
LINE 1: ...ent", "post"."creation_date", "post"."post_type" FROM "post"
                                                                 ^

Watching for file changes with StatReloader
Internal Server Error: /community/
Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: 오류:  "post" 이름의 릴레이션(relation)이 없습니다
LINE 1: ...ent", "post"."creation_date", "post"."post_type" FROM "post"
                                                                 ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\빅프로젝트_34조\bigproject28\community\views.py", line 11, in post_list
    return render(request, 'post_list.html', {'posts': posts})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\defaulttags.py", line 198, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: 오류:  "post" 이름의 릴레이션(relation)이 없습니다
LINE 1: ...ent", "post"."creation_date", "post"."post_type" FROM "post"
                                                                 ^

E:\빅프로젝트_34조\bigproject28\community\views.py changed, reloading.
Watching for file changes with StatReloader
E:\빅프로젝트_34조\bigproject28\community\views.py changed, reloading.
Watching for file changes with StatReloader
User found with email: lhu0770@gmail.com. Username: lhu0770
Authentication failed for email lhu0770@gmail.com. Invalid email or password.
User found with email: lhu0770@gmail.com. Username: lhu0770
User lhu0770@gmail.com authenticated successfully.
Internal Server Error: /community/
Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: 오류:  "post" 이름의 릴레이션(relation)이 없습니다
LINE 1: ...ent", "post"."creation_date", "post"."post_type" FROM "post"
                                                                 ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\빅프로젝트_34조\bigproject28\community\views.py", line 11, in post_list
    return render(request, 'post_list.html', {'posts': posts})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\defaulttags.py", line 198, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: 오류:  "post" 이름의 릴레이션(relation)이 없습니다
LINE 1: ...ent", "post"."creation_date", "post"."post_type" FROM "post"
                                                                 ^

E:\빅프로젝트_34조\bigproject28\aivle_big\routers.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /community/
Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: 오류:  "post" 이름의 릴레이션(relation)이 없습니다
LINE 1: ...ent", "post"."creation_date", "post"."post_type" FROM "post"
                                                                 ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\빅프로젝트_34조\bigproject28\community\views.py", line 11, in post_list
    return render(request, 'post_list.html', {'posts': posts})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\defaulttags.py", line 198, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: 오류:  "post" 이름의 릴레이션(relation)이 없습니다
LINE 1: ...ent", "post"."creation_date", "post"."post_type" FROM "post"
                                                                 ^

Watching for file changes with StatReloader
Internal Server Error: /community/
Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: 오류:  "post" 이름의 릴레이션(relation)이 없습니다
LINE 1: ...ent", "post"."creation_date", "post"."post_type" FROM "post"
                                                                 ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\빅프로젝트_34조\bigproject28\community\views.py", line 11, in post_list
    return render(request, 'post_list.html', {'posts': posts})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\defaulttags.py", line 198, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: 오류:  "post" 이름의 릴레이션(relation)이 없습니다
LINE 1: ...ent", "post"."creation_date", "post"."post_type" FROM "post"
                                                                 ^

Internal Server Error: /community/
Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: 오류:  "post" 이름의 릴레이션(relation)이 없습니다
LINE 1: ...ent", "post"."creation_date", "post"."post_type" FROM "post"
                                                                 ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\빅프로젝트_34조\bigproject28\community\views.py", line 11, in post_list
    return render(request, 'post_list.html', {'posts': posts})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\defaulttags.py", line 198, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: 오류:  "post" 이름의 릴레이션(relation)이 없습니다
LINE 1: ...ent", "post"."creation_date", "post"."post_type" FROM "post"
                                                                 ^

E:\빅프로젝트_34조\bigproject28\community\views.py changed, reloading.
Watching for file changes with StatReloader
E:\빅프로젝트_34조\bigproject28\community\views.py changed, reloading.
Watching for file changes with StatReloader
E:\빅프로젝트_34조\bigproject28\community\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /community/
Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: 오류:  "post" 이름의 릴레이션(relation)이 없습니다
LINE 1: ...ent", "post"."creation_date", "post"."post_type" FROM "post"
                                                                 ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\빅프로젝트_34조\bigproject28\community\views.py", line 12, in post_list
    return render(request, 'post_list.html', {'posts': posts})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\defaulttags.py", line 198, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: 오류:  "post" 이름의 릴레이션(relation)이 없습니다
LINE 1: ...ent", "post"."creation_date", "post"."post_type" FROM "post"
                                                                 ^

E:\빅프로젝트_34조\bigproject28\aivle_big\routers.py changed, reloading.
Watching for file changes with StatReloader
E:\빅프로젝트_34조\bigproject28\community\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /community/
Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: 오류:  "post" 이름의 릴레이션(relation)이 없습니다
LINE 1: ...ent", "post"."creation_date", "post"."post_type" FROM "post"
                                                                 ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\빅프로젝트_34조\bigproject28\community\views.py", line 12, in post_list
    return render(request, 'post_list.html', {'posts': posts})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\defaulttags.py", line 198, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: 오류:  "post" 이름의 릴레이션(relation)이 없습니다
LINE 1: ...ent", "post"."creation_date", "post"."post_type" FROM "post"
                                                                 ^

E:\빅프로젝트_34조\bigproject28\community\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
User found with email: lhu0770@gmail.com. Username: lhu0770
Authentication failed for email lhu0770@gmail.com. Invalid email or password.
Bad Request: /login/send_verification_email/
User found with email: lhu0770@gmail.com. Username: lhu0770
User lhu0770@gmail.com authenticated successfully.
Internal Server Error: /community/
Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: 오류:  "post" 이름의 릴레이션(relation)이 없습니다
LINE 1: ...ent", "post"."creation_date", "post"."post_type" FROM "post"
                                                                 ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\빅프로젝트_34조\bigproject28\community\views.py", line 12, in post_list
    return render(request, 'post_list.html', {'posts': posts})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\defaulttags.py", line 198, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: 오류:  "post" 이름의 릴레이션(relation)이 없습니다
LINE 1: ...ent", "post"."creation_date", "post"."post_type" FROM "post"
                                                                 ^

E:\빅프로젝트_34조\bigproject28\aivle_big\routers.py changed, reloading.
Watching for file changes with StatReloader
E:\빅프로젝트_34조\bigproject28\community\views.py changed, reloading.
Watching for file changes with StatReloader
E:\빅프로젝트_34조\bigproject28\community\urls.py changed, reloading.
Watching for file changes with StatReloader
E:\빅프로젝트_34조\bigproject28\aivle_big\settings.py changed, reloading.
Watching for file changes with StatReloader
User found with email: lhu0770@gmail.com. Username: lhu0770
Authentication failed for email lhu0770@gmail.com. Invalid email or password.
User found with email: lhu0770@gmail.com. Username: lhu0770
User lhu0770@gmail.com authenticated successfully.
Internal Server Error: /community/
Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: 오류:  "post" 이름의 릴레이션(relation)이 없습니다
LINE 1: ...ent", "post"."creation_date", "post"."post_type" FROM "post"
                                                                 ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\빅프로젝트_34조\bigproject28\community\views.py", line 12, in post_list
    return render(request, 'post_list.html', {'posts': posts})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\defaulttags.py", line 198, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: 오류:  "post" 이름의 릴레이션(relation)이 없습니다
LINE 1: ...ent", "post"."creation_date", "post"."post_type" FROM "post"
                                                                 ^

E:\빅프로젝트_34조\bigproject28\community\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Attempting to save post: 1 for user: lhu0770, Email: lhu0770@gmail.com
Error saving post: 오류:  "post" 이름의 릴레이션(relation)이 없습니다
LINE 1: INSERT INTO "post" ("user_id", "title", "content", "creation...
                    ^

E:\빅프로젝트_34조\bigproject28\community\models.py changed, reloading.
Watching for file changes with StatReloader
E:\빅프로젝트_34조\bigproject28\community\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Attempting to save post: 1 for user: lhu0770, Email: lhu0770@gmail.com
Error saving post: 오류:  "post" 이름의 릴레이션(relation)이 없습니다
LINE 1: INSERT INTO "post" ("user_id", "title", "content", "creation...
                    ^

Watching for file changes with StatReloader
Internal Server Error: /community/
Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: 오류:  "post" 이름의 릴레이션(relation)이 없습니다
LINE 1: ...ent", "post"."creation_date", "post"."post_type" FROM "post"
                                                                 ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\빅프로젝트_34조\bigproject28\community\views.py", line 12, in post_list
    return render(request, 'post_list.html', {'posts': posts})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\template\defaulttags.py", line 198, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\lhu07\anaconda3\envs\big_project\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: 오류:  "post" 이름의 릴레이션(relation)이 없습니다
LINE 1: ...ent", "post"."creation_date", "post"."post_type" FROM "post"
                                                                 ^

Watching for file changes with StatReloader
Authentication failed. No user found with email: lhu0770@gmail.com.
Authentication failed. No user found with email: lhu0770@gmail.com.
Attempting to save post: 1 for user: lhu0770, Email: lhu0770@gmail.com
Post saved successfully with ID: 1
Watching for file changes with StatReloader
User found with email: lhu0770@gmail.com. Username: lhu0770
Authentication failed for email lhu0770@gmail.com. Invalid email or password.
User found with email: lhu0770@gmail.com. Username: lhu0770
User lhu0770@gmail.com authenticated successfully.
Watching for file changes with StatReloader
User found with email: lhu0770@gmail.com. Username: lhu0770
Authentication failed for email lhu0770@gmail.com. Invalid email or password.
Watching for file changes with StatReloader
E:\빅프로젝트_34조\be_login\bigproject28\aivle_big\settings.py changed, reloading.
Watching for file changes with StatReloader
E:\빅프로젝트_34조\be_login\bigproject28\aivle_big\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Attempting to save post: 1 for user: lhu0770, Email: lhu0770@gmail.com
Post saved successfully with ID: 1
